# Generated by Django 4.0.4 on 2022-04-27 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_jumlah_pendaftar'),
        ('registrant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrant',
            name='event',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
    ]
