# Generated by Django 4.0.4 on 2022-04-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrant', '0002_alter_registrant_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrant',
            name='jumlah',
            field=models.IntegerField(default=1),
        ),
    ]
