# Generated by Django 3.2.12 on 2022-04-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrant', '0004_registrant_is_come'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
