# Generated by Django 3.2.12 on 2022-05-01 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wilayah', '0001_initial'),
        ('registrant', '0005_registrant_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrant',
            name='kursi',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='registrant',
            name='wilayah',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.CASCADE, to='wilayah.wilayah'),
        ),
    ]
