# Generated by Django 3.2.12 on 2022-05-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='kehadiran',
            field=models.IntegerField(default=0),
        ),
    ]
