# Generated by Django 3.2.12 on 2022-05-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_kehadiran'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='blok_kursi',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
