# Generated by Django 3.2.12 on 2022-05-31 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_short_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='short_description',
            new_name='nama_event',
        ),
    ]
