# Generated by Django 3.2.12 on 2022-06-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_rename_short_description_event_nama_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_full_capacity',
            field=models.BooleanField(default=False),
        ),
    ]
