# Generated by Django 3.2.12 on 2022-05-24 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrscan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pin',
            table='pin',
        ),
    ]
